version: "3.8"

services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_DIR: app1  
    ports:
      - "8001:80"
    container_name: fastapi_app1
    environment:
      - PORT=8001


  app2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_DIR: app2
    ports:
      - "8002:80"
    container_name: fastapi_app2
    environment:
      - PORT=8002

  app3:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_DIR: app3
    ports:
      - "8003:80"
    container_name: fastapi_app3
    environment:
      - PORT=8003

  welcome:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_DIR: welcome
    ports:
      - "8004:80"
    container_name: fastapi_welcome
    environment:
      - PORT=8004

  app-v2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_DIR: app-v2
    ports:
      - "8005:80"
    container_name: fastapi_app-v2
    environment:
      - PORT=8005