version: "3.8"

services:
  app1:
    build:
      context: ./app1
      dockerfile: ../Dockerfile
    # ports:
    #   - "8001:80"
    container_name: fastapi_app1
    environment:
      - PORT=8001
    expose:
      - "80"

  app2:
    build:
      context: ./app2
      dockerfile: ../Dockerfile
    # ports:
    #   - "8002:80"
    container_name: fastapi_app2
    environment:
      - PORT=8002
    expose:
      - "80"

  app3:
    build:
      context: ./app3
      dockerfile: ../Dockerfile
    # ports:
    #   - "8003:80"
    container_name: fastapi_app3
    environment:
      - PORT=8003
    expose:
      - "80"

  welcome:
    build:
      context: ./welcome
      dockerfile: ../Dockerfile
    # ports:
    #   - "8004:80"
    container_name: fastapi_welcome
    environment:
      - PORT=800

    expose:
      - "80"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app1
      - app2
      - app3
      - welcome
    container_name: nginx_proxy
