version: "3.8"

services:
  app1:
    build:
      context: ./app1
      dockerfile: ../Dockerfile
    ports:
      - "8001:80"
    container_name: fastapi_app1

  app2:
    build:
      context: ./app2
      dockerfile: ../Dockerfile
    ports:
      - "8002:80"
    container_name: fastapi_app2

  app3:
    build:
      context: ./app3
      dockerfile: ../Dockerfile
    ports:
      - "8003:80"
    container_name: fastapi_app3

  welcome:
    build:
      context: ./welcome
      dockerfile: ../Dockerfile
    ports:
      - "8004:80"
    container_name: fastapi_welcome

  app_accounts:
    build:
      context: ./App_Accounts
      dockerfile: ../Dockerfile
    ports:
      - "8005:80"
    container_name: App_accounts