version: "3.8"

services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_DIR: app1  
    ports:
      - "8001:80"
    container_name: fastapi_app1
    environment:
      - PORT=8001
  
  app-v2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_DIR: app-v2
    ports:
      - "8005:80"
    container_name: fastapi_app-v2
    environment:
      - PORT=8005