version: "3.8"

services:
  app1:
    build:
      # context: ./app1
      context: .
      # dockerfile: ../Dockerfile
      dockerfile: app1/Dockerfile
    ports:
      - "8001:80"
    container_name: fastapi_app1

  app2:
    build:
      context: .
      dockerfile: app2/Dockerfile
    ports:
      - "8002:80"
    container_name: fastapi_app2

  app3:
    build:
      context: .
      dockerfile: app3/Dockerfile
    ports:
      - "8003:80"
    container_name: fastapi_app3

  welcome:
    build:
      context: .
      dockerfile: welcome/Dockerfile
    ports:
      - "8004:80"
    container_name: fastapi_welcome
