version: "3.8"

services:
  app1:
    build:
      context: ./app1
      dockerfile: ../Dockerfile
    ports:
      - "8001:80"
    container_name: fastapi_app1

  app2:
    build:
      context: ./app2
      dockerfile: ../Dockerfile
    ports:
      - "8002:80"
    container_name: fastapi_app2
