# Generated by Django 4.2.5 on 2023-12-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Accounts', '0003_rename_name_user_username_remove_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='dd', upload_to='prof_pic'),
            preserve_default=False,
        ),
    ]
