name: Deploy to Development-V2
on:
  push:
    branches: 
      - dev-v2
jobs:
  Development-V2-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_V2_DEV_IP }}
          username: ${{ secrets.EC2_DEV_USERNAME }}
          key: ${{ secrets.EC2_DEV_SECRET }}
          port: 22
          script: |
            export COMMIT_SHORT=${GITHUB_SHA::8}
            echo $COMMIT_SHORT >> commit-short.txt
            /bin/bash -e /home/ubuntu/scripts/pipeline.sh
          envs: GITHUB_SHA,COMMIT_SHORT
